;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-opening
	autopair-insert-or-skip-quote
	autopair-newline
	autopair-skip-close-maybe
	c-electric-semi&comma
	c-indent-line-or-region
	electric-newline-and-maybe-indent
	ignore
	indent-for-tab-command
	kill-region
	org-cycle
	org-force-self-insert
	))

(setq mc/cmds-to-run-once
      '(
	handle-switch-frame
	kmacro-end-macro
	mouse-set-region
	org-beginning-of-line
	org-end-of-line
	org-self-insert-command
	php-show-arglist
	query-replace
	))
